services:
  #### Commented out for the time being...will be active soon!!!


  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:0.2.8
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./conf/tiled/deploy:/config:z
      - ./data:/data:z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://tiled:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    hostname: tiled
    networks:
      gisax_net1:
  beamline_sim:
    command: python -m arroyosas.app.tiled_event_sim_cli /app/tiled_event_logs
    image: ghcr.io/als-computing/arroyosas:main
    restart: unless-stopped
    volumes:
      - .:/app:Z
      - ./settings.yaml:/app/settings.yaml:z
      - ./tiled_event_logs/:/app/tiled_event_logs:z
    networks:
      gisax_net1:

  lse_operator:
    command: python -m arroyopy.cli run block_configs/lse_operator_block.yaml
    build:
      context: .
    restart: unless-stopped
    environment:
      TILED_API_KEY: ${TILED_SINGLE_USER_API_KEY}
    ports:
      - "8021:8021"
    volumes:
      - .:/app:Z
      - ./block_configs:/app/block_configs:Z
    networks:
      gisax_net1:

  # viz_operator:
  #   command: python -m arroyosas.app.viz_operator_cli
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   ports:
  #     - "8021:8021"
  #   volumes:
  #     - .:/app:Z
  #     - ./settings.yaml:/app/settings.yaml:Z
  #   networks:
  #     gisax_net1:

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_frontend
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app:Z
  #   networks:
  #     gisax_net1:


  kvrocks:
    image: docker.io/apache/kvrocks:latest
    volumes:
      - ./conf/kvrocks/kvrocks.conf:/etc/kvrocks/kvrocks.conf
      - ./persist/kvrocks/data:/data
    networks:
      gisax_net1:
    ports:
      - "127.0.0.1:6666:6666"

networks:
  gisax_net1:
    driver: bridge
