services:
  #### Commented out for the time being...will be active soon!!!


  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:0.1.0-b17
    ports:
      - "8000:8000"
    environment:
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./conf/tiled/deploy:/deploy:Z
      - ./data:/data:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://tiled:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    hostname: tiled
    networks:
      gisax_net1:
  beamline_sim:
    command: python -m arroyosas.app.tiled_poller_sim_cli
    image: ghcr.io/als-computing/arroyosas:main
    restart: unless-stopped
    volumes:
      - .:/app:Z
      - ./settings.yaml:/app/settings.yaml:Z
    networks:
      gisax_net1:

  lse_operator:
    command: python -m arroyogisaxs.app.kse_operator_cli
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8021:8021"
    volumes:
      - .:/app:Z
      - ./settings.yaml:/app/settings.yaml:Z
    networks:
      gisax_net1:
  viz_operator:
    command: python -m arroyosas.app.viz_operator_cli
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8021:8021"
    volumes:
      - .:/app:Z
      - ./settings.yaml:/app/settings.yaml:Z
    networks:
      gisax_net1:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/app:Z
    networks:
      gisax_net1:

  tiled_poller:
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m arroyosas.app.tiled_poller_cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:Z
      - ./settings_container.yaml:/app/settings.yaml:Z
      - ./data:/data:Z
    ports:
      - "5678:5678"
    hostname: tiled_poller
    networks:
      gisax_net1:


  kvrocks:
    image: docker.io/apache/kvrocks:latest
    volumes:
      - ./conf/kvrocks/kvrocks.conf:/etc/kvrocks/kvrocks.conf
      - ./persist/kvrocks/data:/data
    networks:
      gisax_net1:
    ports:
      - "127.0.0.1:6666:6666"

networks:
  gisax_net1:
    driver: bridge
