FROM node:18-alpine AS builder

WORKDIR /frontend
COPY ./frontend/package*.json /frontend/
RUN npm ci
COPY ./frontend /frontend/
COPY .env_frontend /frontend/.env
RUN npm run build

FROM docker.io/nginx:1.26-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /frontend/build/ /usr/share/nginx/html/
COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
