services:
  #### Commented out for the time being...will be active soon!!!
  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:0.1.0-b17
    ports:
      - "8000:8000"
    environment:
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./conf/tiled/deploy:/deploy:Z
      - ./data:/data:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://tiled:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    hostname: tiled
    networks:
      gisax_net1:

  # processor:
  #   command: python -m tr_ap_xps.apps.processor_cli
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_processor
  #   restart: unless-stopped
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - .:/app:Z
  #     - ./settings_container.yaml:/app/settings.yaml:Z
  #   networks:
  #     gisax_net:
  #   depends_on:
  #     tiled:
  #       condition: service_healthy
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_frontend
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app:Z
  #   networks:
  #     gisax_net:

  tiled_poller:
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m arroyogisaxs.app.tiled_poller_cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:Z
      - ./settings_container.yaml:/app/settings.yaml:Z
      - ./data:/data:Z
    ports:
      - "5678:5678"
    hostname: tiled_poller
    networks:
      gisax_net1:


  kvrocks:
    image: docker.io/apache/kvrocks:latest
    ports:
      - "6666:6666"
    volumes:
      - ./conf/kvrocks/kvrocks.conf:/etc/kvrocks/kvrocks.conf
      - ./persist/kvrocks/data:/data
    networks:
      gisax_net1:

networks:
  gisax_net1:
    driver: bridge
