[project]
name = "arroyoGISAXS"
version = "0.0.1"
channels = ["conda-forge"]
platforms = ["linux-64"]



[tasks]
pre-commit-install = "pre-commit install"
pre-commit = "pre-commit run --all-files"
start_ws = "python -m arroyogisaxs.websockets"

[dependencies]

[host-dependencies]
pre-commit = ">=3.0"

[pypi-dependencies]
arroyoGISAXS = { path = ".", editable = true }
arroyopy = "*"
astropy = "*"
dynaconf = "*"
python-dotenv = "*"
pandas = "*"
msgpack = "*"
numpy = "*"
Pillow = "*"
pyzmq = "*"
tqdm = "*"
typer = "*"
websockets = "*"
zarr = "*"
tiled = ">=0.1.0b14, <0.2"

[feature.dev]
dependencies = { flake8 = "*", pre-commit = "*", pytest-asyncio = "*", pytest-mock = "*", tiled = "*" }

[feature.notebook]
dependencies = { jupyterlab = "*", matplotlib = "*", python-dotenv = "*" }

[feature.simulator]
dependencies = { h5py = "*" }

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }
simulator = { features = ["simulator"], solve-group = "default" }
