[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "arroyoGISAXS"
version = "0.0.1"
description = "A package to perform computations and suggestions during a time-resolved GISAXS experiment."
authors = [{ name = "Dylan McReynolds", email = "dmcreynolds@lbl.gov" }]
dependencies = []  # Leave this empty, managed in Pixi


[tool.isort]
profile = "black"


[tool.pixi.project]
name = "arroyoGISAXS"
version = "0.0.1"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]
pre-commit-install = "pre-commit install"
pre-commit = "pre-commit run --all-files"
start_ws = "python -m arroyogisaxs.websockets"

[tool.pixi.dependencies]

[tool.pixi.host-dependencies]
pre-commit = ">=3.0"

[tool.pixi.pypi-dependencies]
arroyoGISAXS = { path = ".", editable = true }
arroyopy = "*"
astropy = "*"
dynaconf = "*"
python-dotenv = "*"
pandas = "*"
msgpack = "*"
numpy = "*"
Pillow = "*"
pyzmq = "*"
tqdm = "*"
typer = "*"
websockets = "*"
zarr = "*"
tiled = ">=0.1.0b14, <0.2"

[tool.pixi.feature.dev]
dependencies = { flake8 = "*", pre-commit = "*", pytest-asyncio = "*", pytest-mock = "*", tiled = "*" }

[tool.pixi.feature.notebook]
dependencies = { jupyterlab = "*", matplotlib = "*", python-dotenv = "*" }


[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }