---
logging_level: DEBUG

tiled_poller:
  zmq_frame_publisher:
    address: tcp://0.0.0.0:5000  #only safe in containers
  poll_interval: 5 # seconds
  uri: https://tiled.nsls2.bnl.gov
  api_key: "@format {env[TILED_LIVE_API_KEY]}"
  runs_segments:
    - smi
    - raw
  frames_segments:
    - primary 
    - data
    # - 
    - pil1M_image
    
viz_operator:
  listener:
    zmq_address: tcp://0.0.0.0:5000  #only safe in containers
  tiled:
    raw:
      uri: https://tiled.nsls2.bnl.gov
      api_key: "@format {env[TILED_LIVE_API_KEY]}"
  redis:
    host: kvrocks
    port: 6666
  ws_publisher:
    host: 0.0.0.0
    port: 8020

tiled_processed:
  uri: https://tiled.nsls2.bnl.gov
  api_key: "@format {env[TILED_LIVE_API_KEY]}"
  root_segments:
    - smi
    - sandbox
    - viz
    - tmp


  models:
    - name: CNNAutoencoder
      checkpoint_dir: /torch/cnnautoencoder
      python_class: CNNAutoencoder
      type: torch
      proceosors: gpu

    - name: PCA
      dir: /dim_reduction/pca
      current: PCA
      type: joblib
      processor: cpu


  current_latent_space: CNNAutoencoder
  current_dim_reduction: CNNAutoencoder
    # - name: UMAP
    #   directory: /dim_reduction/umap
  current_reduction: PCA

lse:
  zmq_router_address: tcp://*:5555
  zmq_router_hwm: 100000
  zmq_dealer_address: tcp://*:5556
  websocket_publish_host: 0.0.0.0
  websocket_publish_port: 8021
  zmq_publish_address: tcp://*:5557


frame_publisher:
  zmq_publish_address: tcp://*:5558

lse_operator:
  ws_publisher:
    host: 0.0.0.0
    port: 8765
  zmq_publisher: # ???
    zmq_address: tcp://0.0.0.0:5557
  listener:
    zmq_address: tcp://0.0.0.0:5000
  zmq_broker:
    router_address: tcp://0.0.0.0:5555
    router_hwm: 100000

dynaconf_merge: true