---
logging_level: DEBUG

tiled_poller:
  single_run:  3e253a6d-ba56-483a-b663-5cb2176c33c2 # If set, will repeatedly poll this run
  zmq_frame_publisher:
    address: tcp://0.0.0.0:5000  #only safe in containers
  poll_interval: 5 # seconds
  uri: https://tiled.nsls2.bnl.gov
  api_key: "@format {env[TILED_LIVE_API_KEY]}"
  websocket_url: "ws://tiled:8000/stream"  # change it
  runs_segments:
    - smi
    - raw
  frames_segments:
    - primary 
    - data
    # - 
    - pil1M_image
    
viz_operator:
  listener:
    zmq_address: tcp://tiled_poller:5000  #only safe in containers
  tiled:
    raw:
      uri: https://tiled.nsls2.bnl.gov
      api_key: "@format {env[TILED_LIVE_API_KEY]}"
  redis:
    host: kvrocks
    port: 6666
  ws_publisher:
    host: 0.0.0.0
    port: 8020

tiled_processed:
  uri: https://tiled.nsls2.bnl.gov
  api_key: "@format {env[TILED_LIVE_API_KEY]}"
  root_segments:
    - smi
    - sandbox
    - viz
    - tmp

lse_reducer:
  models:
    - name: CNNAutoencoder
      state_dict: ./models/cnn_autoencoder/model_state_dict.npz
      python_class: CNNAutoencoder
      python_file: ./models/cnn_autoencoder/model.py
      type: torch
    
    - name: AE
      state_dict: ./models/ae_v1/ae_model_finetuned.npz
      python_class: CNNAutoencoder
      python_file: ./models/ae_v1/ae.py
      type: torch

    - name: UMAP
      file: ./models/umap/quick_test.joblib
      type: joblib

  current_latent_space: AE
  current_dim_reduction: UMAP

lse_broker:
  dealer_address: tcp://0.0.0.0:5555
  router_address: tcp://0.0.0.0:5556
  router_hwm: 100000

lse_worker:
  broker:
    dealer_address: tcp://lse_broker:5556
    

frame_publisher:
  zmq_publish_address: tcp://*:5558

lse_operator:
  ws_publisher:
    host: 0.0.0.0
    port: 8765
  zmq_publisher: # ???
    zmq_address: tcp://0.0.0.0:5557
  listener:
    zmq_address: tcp://tiled_poller:5000
  zmq_broker:
    router_address: tcp://lse_broker:5555
    router_hwm: 100000

dynaconf_merge: true