---
logging_level: INFO


models:
  models_root_dir: /data/models
  torch_models:
    - name: CNNAutoencoder
      checkpoint_dir: /torch/cnnautoencoder
      python_class: CNNAutoencoder

  dim_reduction_models:
    - name: PCA
      dir: /dim_reduction/pca

    # - name: UMAP
    #   directory: /dim_reduction/umap

tiled_poller:
  publish_address: 0.0.0.0  #only safe in containers
  publish_port: 5000

viz_operator:
  listen_port: 5000
  listen_address: 0.0.0.0  #only safe in containers
  redis_host: redis
  redis_port: 6379
  websocket_publish_host: 0.0.0.0
  websocket_publish_port: 8021
