---
logging_level: INFO

tiled_poller:
  publish_address: 0.0.0.0  #only safe in containers
  publish_port: 5000

viz_operator:
  listen_port: 5000
  listen_address: 0.0.0.0  #only safe in containers
  redis_host: redis
  redis_port: 6379
  websocket_publish_host: 0.0.0.0
  websocket_publish_port: 8021

  models:
    - name: CNNAutoencoder
      checkpoint_dir: /torch/cnnautoencoder
      python_class: CNNAutoencoder
      type: torch

    - name: PCA
      dir: /dim_reduction/pca
      current: PCA
      type: joblib


  current_latent_space: CNNAutoencoder
  current_dim_reduction: CNNAutoencoder
    # - name: UMAP
    #   directory: /dim_reduction/umap
  current_reduction: PCA
