---
logging_level: INFO
tiled_poller:
  publish_address: tcp://0.0.0.0:5000  #only safe in containers



lse_reducer:
  models:
    - name: CNNAutoencoder
      state_dict: ./models/cnn_autoencoder/model_state_dict.npz
      python_class: CNNAutoencoder
      python_file: ./models/cnn_autoencoder/model.py
      type: torch

    - name: UMAP
      file: ./models/umap/quick_test.joblib
      type: joblib

  current_latent_space: CNNAutoencoder
  current_dim_reduction: UMAP

lse_operator:
  ws_publisher:
    host: 0.0.0.0
    port: 8765
  zmq_publisher: # ???
    zmq_address: tcp://0.0.0.0:5557
  listener:
    zmq_address: tcp://0.0.0.0:5000
  zmq_broker:
    router_address: tcp://0.0.0.0:5555
    router_hwm: 100000
    dealer_address: tcp://0.0.0.0:5556
lse_publisher:
  ws_publisher:
    host: 0.0.0.0
    port: 8021

viz_operator:
  ws_publisher:
    host: 0.0.0.0
    port: 8021
  listener:
    zmq_address: tcp://0.0.0.0:5000  #only safe in containers
  redis:
    host: kvrocks
    port: 6666
  tiled:
    raw:
      # uri: http://tiled:8000
      uri: https://tiled.nsls2.bnl.gov
      # api_key: "env[TILED_API_KEY]"

tiled_processed:
  uri: http://tiled:8000

smi_tiled_image_path: /primary/data/pil900KW_image

dynaconf_merge: true
