name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Cache Pixi Environment
        uses: actions/cache@v3
        with:
          path: ~/.pixi/envs
          key: pixi-${{ runner.os }}-${{ hashFiles('pixi.lock') }}
          restore-keys: pixi-${{ runner.os }}-

      - name: Install Dependencies
        run: pixi install
